function volver(){
    location.href = "http://127.0.0.1:5500/HTML/Ventana_Principal.html";
}
function mostrar1(){
    document.getElementById("frame1").style.display="none";
}
function ocultar1(){
    document.getElementById("frame1").style.display="block";
}
function mostrar2(){
    document.getElementById("frame2").style.display="none";
}
function ocultar2(){
    document.getElementById("frame2").style.display="block";
}